controllers/CurrencyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Currency;
use app\models\CurrencySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CurrencyController implements the CRUD actions for Currency model.
 */
class CurrencyController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Currency models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CurrencySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Currency model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Currency model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Currency();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Currency model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Currency model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Currency model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Currency the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Currency::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionGet()
    {
        $model = new Currency();
        //$model = $this->findModel($id);

        return $this->render('get', ['model' => $model]);
    }
}

controllers/PrivozController.php
<?php

namespace app\controllers;

use app\models\PrivozParser;
use app\models\Privoz;
use app\models\PrivozSearch;
use Yii;
use yii\web\Controller;
use app\models\UploadprivozForm;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

class PrivozController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $searchModel = new PrivozSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=100;

        foreach($dataProvider->getModels() as $model)
        {
            if ($model->count_phones_in_base == 0)
                $model->checkInBase();
        }

        $aLastPrivoz = Privoz::getLastPrivoz();

        // Кеширование Действий на 10 минут
        $aActions = Yii::$app->cache->get('actions');
        if ($aActions === false)
        {
            $aActions = ArrayHelper::map(Privoz::find('action', 'action')->distinct()->all(), 'action', 'action');
            Yii::$app->cache->set('actions', $aActions, 600);
        }

        // Кеширование Рубрик на 10 минут
        $aRubriks = Yii::$app->cache->get('rubriks');
        if ($aRubriks === false)
        {
            $aRubriks = ArrayHelper::map(Privoz::find('razdel', 'razdel')->distinct()->all(), 'razdel', 'razdel');
            Yii::$app->cache->set('rubriks', $aRubriks, 600);
        }

        return $this->render('index', [
            'aLastPrivoz' => $aLastPrivoz,  // данные о последнем выпуске привоза
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'aActions' => $aActions,
            'aRubriks' => $aRubriks,
        ]);

    }

    public function actionUploadfile()
    {


        $model = new UploadprivozForm();

        if (Yii::$app->request->isPost) {

            $model->privozFile = UploadedFile::getInstance($model, 'privozFile');

            if ($model->upload()) {
                // проверяем есть ли уже такой выпуск привоза

//                if ((Privoz::getLastPrivoz()['year'] == date("Y")) && (Privoz::getLastPrivoz()['vypusk'] == $model->privozNumber))
                if (Privoz::isVypuskInDB(date("Y"), $model->privozNumber)) {
                    $result = 2; // уже есть такой выпуск
                } else {

                    $oPrivozParser = new PrivozParser($model->finalFileName, $model->privozNumber);
                    $result = 1; // Новый выпуск загружен
                }
                return $this->render('upload', ['model' => $model, 'result' => $result]);
            }
        }

        return $this->render('upload', ['model' => $model]);
    }

    // Пересчитываем количество телефонов в текущем выпуске Привоза
    public function actionRecountphones()
    {
        $aLastVypusk = Privoz::getLastPrivoz();
        if ($aLastVypusk)
        {
            Privoz::recoundAdsPronesCount($aLastVypusk['year'], $aLastVypusk['vypusk']);
        }

        // последний выпуск привоза
        return $this->render('recountphones');
    }

    // помечаем конкурентов в текущем выпуске Привозад
    public function actionSetagetnts()
    {
        $aLastVypusk = Privoz::getLastPrivoz();
        if ($aLastVypusk)
        {
            Privoz::setAgents($aLastVypusk['year'], $aLastVypusk['vypusk']);
        }

        //return $this->render('recountphones');
    }

    public function actionLastvypusk()
    {
        return $this->redirect(['/privoz',
            'PrivozSearch[year]' => \app\models\Privoz::getLastPrivoz()['year'],
            'PrivozSearch[vypusk]' => \app\models\Privoz::getLastPrivoz()['vypusk'],
            'PrivozSearch[is_agent]' => 0,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'АН "Интеграл" Запорожье',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    // Вот так делать во вьюхах нельзя :)
    $usd = \app\models\Currency::findOne('USD');

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
//            ['label' => 'Home', 'url' => ['/site/index']],
            [
                'label' => 'База',
                'url' => ['/object-flats']
            ],
            [
                'label' => 'Привоз',
                'url' => ['/privoz/lastvypusk',]
            ],


            ['label' => 'Конкуренты', 'url' => ['/phones/index?sort=-updated']],
            [
                'label' => 'USD ['.$usd['bid'].'] ['.$usd['ask'].']',
                'url' => ['/currency/get'],
                'options' => [
                    'style' => 'color: red',
                ]
            ],
//            ['label' => 'Contact', 'url' => ['/site/contact']],
//            Yii::$app->user->isGuest ? (
//                ['label' => 'Login', 'url' => ['/site/login']]
//            ) : (
//                '<li>'
//                . Html::beginForm(['/site/logout'], 'post')
//                . Html::submitButton(
//                    'Logout (' . Yii::$app->user->identity->username . ')',
//                    ['class' => 'btn btn-link']
//                )
//                . Html::endForm()
//                . '</li>'
//            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; АН "Интеграл" Запорожье <?= date('Y') ?></p>

        <p class="pull-right">Программа работает <?php $datetime1 = new DateTime();
            $datetime2 = new DateTime('2015-12-07 15:00:00');
            $interval = $datetime1->diff($datetime2);
            $elapsed = $interval->format('%y лет %m месяцев %d дней %h часов %i минут %S секунд');
            echo $elapsed;
            ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>